# Setup
title: Clay Carson
tagline:
url: http://beta.claycarson.net
paginate: 1
baseurl: ""

sass:
  sass_dir: _sass
  style: :compressed

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: UA-56506919-1

# Specify the author for blog posts
author:
  name: Clay Carson
  url: https://claycarson.net
  email: clay@claycarson.net

# This is the list of pages to include in the header of the website.
#pages_list:
#  Photos: '/photos'
#  Newsletter: '/newsletter'

# Permalinks
permalink: /:categories/:year/:month/:day/:title

# Deploy
deploy:
  directory: _site